### ISSUE TITLE
Message ID parsing fails if no new line exists after value

### ISSUE THREAD

**Issue by wingiti** [GOVCERT-LU/eml_parser#58]
I received a mail where the header looked like below:
```
...
Date: Fri, 19 Feb 2021 19:36:50 +0000
Message-ID:  
 <some@something.com>MIME-Version: 1.0
Accept-Language: en-US, en-GB
...
```

After parsing it:
```
ep = eml_parser.EmlParser(include_raw_body=True)
parsed_eml = ep.decode_email_bytes(raw_email)
```

The value of `parsed_eml["header"]["header"]["message-id"][0]` looked like this:
`<some@something.com>MIME-Version: 1.0`

**Comment by sim0nx** [comment]
As far as I can tell that is expected behavior as your input is broken. "MIME-Version" should be on a new line, not part of the value of "Message-ID".

**Comment by wingiti** [comment]
I can understand your response but if you use the eml_parser for analyzing suspicious/malicious/spam/phishing/... mails you will receive sometimes messages that do not fit the rules.
Not only for this issue. From time to time the module crashes at all during parsing such messages.

The input is not broken from a technical perspective. It was received like presented above.
Just wanted to mention this issue.

**Comment by sim0nx** [comment]
> I can understand your response but if you use the eml_parser for analyzing suspicious/malicious/spam/phishing/... mails you will receive sometimes messages that do not fit the rules.

I know, that is the primary use-case of this lib and we try hard to work around broken mails but it is not always possible due to various reasons to cover all cases.

> Not only for this issue. From time to time the module crashes at all during parsing such messages.

Please do open issues for those cases, the goal is to be able to parse as much of those bad mails as possible and to absolutely not "crash". If you see crash cases please do provide a sample via the issue or by e-mail.

> The input is not broken from a technical perspective. It was received like presented above.

The fact that it was received like that does not make it technically correct though. Mail-servers don't care about that kind of headers.
According to the RFCs it is not valid to have "<some@something.com>MIME-Version: 1.0", there is a newline missing.

> Just wanted to mention this issue.

Absolutely, appreciated!
If you have an idea to fix your case, please feel free to elaborate or open a PR.
