### ISSUE TITLE
Module working intermittently

### ISSUE THREAD

**Issue by quimmontal** [GOVCERT-LU/eml_parser#6]
Hi @sim0nx,

First of all thanks for the module, it helped a lot easing procedures. I have been testing it and I saw that the module sometimes is not working as expected. I am using the following:

m = eml_parser.decode_email(k, include_raw_body=True)

to extract the data from the eml and getting the urls, but the same code with the same eml being processed, half of the times gets the text and process correctly all the data and the other half doesn't get it.  The header gets processed always though.

As no error is being prompted, I have no idea what is the source of the problem. Have you seen this error before or do you have any idea of what the problem could be?

Thanks in advance :)

**Comment by sim0nx** [comment]
Hi @quimmontal 

I am glad it is useful for you :-)

Mail parsing is not always easy / error-free, as mails are sometimes quite funky in their format.
We have seen weird behaviour before and as far as our sample base goes, have fixed them all.

If you don't mind sending me an anonymized sample which fails for you, I could have a look to see what the problem is? (georges . toth @ govcert . etat . lu)

**Comment by quimmontal** [comment]
After checking with @sim0nx, there was no issue with the module itself, but I was not iterating over the body in order to get the data on all body parts.

The solution, was to loop through all body parts (txt/html mime-part), as it
and it will not fail if there are no URI's found (note the get('uri',
[]) which will return an empty array if none found).

Example code:
  for body_ in body:
      for i in body_.get('uri', []):
          if 'urldefense' in i:
              p = ppdecode(i)
              urls.append(p.url)

Thanks for your help @sim0nx!
